server:
  port: 9999

# mysql
spring:
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools: 
    restart: 
      #热部署生效
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true


